http:
  middlewares:
    tasksautomation-apidog-stripprefix:
      stripPrefix:
        prefixes:
          - /docs

  services:
    tasksautomation-apidog:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://pe1hme405o.apidog.io

  routers:
    tasksautomation-apidog-docs:
      rule: Host(`tasksautomation.lucaskaiut.com.br`) && PathPrefix(`/docs`)
      entryPoints:
        - websecure
      middlewares:
        - tasksautomation-apidog-stripprefix
      service: tasksautomation-apidog
      tls:
        certResolver: letsencrypt
      priority: 100
