name: infra-edge

services:
  traefik:
    image: traefik:v3.6
    container_name: infra_traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ../../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/static/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN:?defina DOMAIN no .env}`)
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-dashboard.service=api@internal

networks:
  edge:
    name: infra_edge

volumes:
  traefik_letsencrypt:
