#!/bin/bash
set -euo pipefail
mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
CREATE DATABASE IF NOT EXISTS \`${EMATRICULA_DB_NAME}\`;
CREATE USER IF NOT EXISTS '${EMATRICULA_DB_USER}'@'%' IDENTIFIED BY '${EMATRICULA_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${EMATRICULA_DB_NAME}\`.* TO '${EMATRICULA_DB_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
