APP_COMPOSE_DIR="stacks/apps/build-runner"
APP_GIT_SUBDIR="android-build-runner"
APP_GIT_REMOTE="git@github.com:lucaskaiut/android-build-runner.git"
APP_GIT_BRANCH="${APP_GIT_BRANCH:-main}"
APP_GIT_USE_SSH=1
: "${APP_USE_SWARM:=1}"
: "${APP_SWARM_STACK_NAME:=infra-app-build-runner}"
: "${APP_SWARM_COMPOSE_FILE:=docker-stack.yml}"
APP_HTTP_PROBE_SERVICE_HOST="runner"
APP_HTTP_PROBE_PATH="/up"
APP_DEPLOY_SUBPATH_GUARD="api"
APP_SWARM_FORCE_SERVICE_UPDATE=1
APP_SWARM_FORCE_IMAGE="local/build-runner-api:latest"
APP_SWARM_FORCE_SERVICE_ROLES="app scheduler"
