APP_COMPOSE_DIR="stacks/apps/ematricula"
APP_GIT_SUBDIR="ematricula"
APP_GIT_REMOTE="https://github.com/lucaskaiut/ematricula.git"
APP_GIT_BRANCH="${APP_GIT_BRANCH:-main}"
APP_COMPOSE_SCALES="app=2"
APP_HTTP_PROBE_SERVICE_HOST="ematricula-api"
